### ISSUE TITLE
Issue with newest wallet and p2p connections?

### ISSUE THREAD

**Issue by Kiefff** [kr1z1s/p2pool-linx#1]
After updating to most recent wallet, seems to get stuck at startup when testing bitcoind P2P connections and just sits there.

...taking a while. Common reasons for this include all of bitcoind's connection slot being used

thanks

**Comment by pfreak2000** [comment]
same problem here

**Comment by kr1z1s** [comment]
Thanx

https://github.com/kr1z1s/p2pool-linx/commit/c67f723ebd9ee72fae8c1364a8cde7ed656bf913

Closed
