### ISSUE TITLE
A MAJORITY OF SHARES CONTAIN A VOTE FOR AN UNSUPPORTED SHARE IMPLEMENTATION

### ISSUE THREAD

**Issue by pfreak2000** [kr1z1s/p2pool-linx#2]
A MAJORITY OF SHARES CONTAIN A VOTE FOR AN UNSUPPORTED SHARE IMPLEMENTATION! (v17 with 78% support) An upgrade is likely necessary. Check http://p2pool.forre.st/ for more information.

**Comment by kr1z1s** [comment]
Tested the new version.
Updates later.

**Comment by pfreak2000** [comment]
thanks, can you create other p2pools ?
i will setup a p2pool for trezarcoin, gobyte, vivo and Verge-Lyra2REv2(XVG) but i found no repository

**Comment by kr1z1s** [comment]
https://github.com/kr1z1s/p2pool-linx/commit/f1638af134eb704f825fa07a537318352f2bb087
